### ISSUE TITLE
请问这个插件的生成规则是什么？

### ISSUE THREAD

**Issue by coderhsw** [252860883/ArtQRCode#2]
我看了下插件的源码，只看出来了使用图片的高宽比是有规定的，但是那个图片生成的数量的规律我没看出来，求指教

**Comment by 252860883** [comment]
图片生成的规律是根据数组遍历判断实现的，比如：当竖列四个点都是1的时候会进行row4图片的绘制。

**Comment by coderhsw** [comment]
貌似按照这个判断，会有很多空出来的地方，特别是没有使用single的时候。

**Comment by 252860883** [comment]
是的，single是必填的，最近我在封装这个库，这块的逻辑有做优化，没有single的时候会填充默认颜色。

**Comment by coderhsw** [comment]
好的大佬👍
我看那个图片绘制的判断逻辑，没看出图片数量的规律，请问是随机的吗？

**Comment by 252860883** [comment]
> 好的大佬👍
> 我看那个图片绘制的判断逻辑，没看出图片数量的规律，请问是随机的吗？

已经更新了readme文档，图片绘制的核心逻辑在 Drawing.prototype.draw() 方法中。
