### ISSUE TITLE
请问可以支持二维码中间位置放置logo吗

### ISSUE THREAD

**Issue by mobljs** [252860883/ArtQRCode#3]

**Comment by 252860883** [comment]
暂时没有开发这个功能，但是您可以新建一个canvas画布，用生成的二维码打底，在新建的canvas画布上添加自定义的二维码再生成图片。

**Comment by 252860883** [comment]
暂时没有开发这个功能，但是您可以新建一个canvas画布，用生成的二维码打底，在新建的canvas画布上添加自定义的logo，然后再生成图片。
